/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-18 10:08:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/common/errorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"resources/css/joinAdmin.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\"> \n");
      out.write("<style>\n");
      out.write("	@font-face {\n");
      out.write("	    font-family: 'MinSans-Regular';\n");
      out.write("	    src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/MinSans-Regular.woff') format('woff');\n");
      out.write("	    font-weight: normal;\n");
      out.write("	    font-style: normal;\n");
      out.write("	}\n");
      out.write("	@font-face {\n");
      out.write("	    font-family: 'MinSans-Bold';\n");
      out.write("	    src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/MinSans-Bold.woff') format('woff');\n");
      out.write("	    font-weight: normal;\n");
      out.write("	    font-style: normal;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body style=\"margin: 0px; background-color: #FFFBF2;\">\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("	<div class=\"mainDiv\">\n");
      out.write("		<div class=\"joinAdmin title\">\n");
      out.write("			<p>관리자 회원가입</p>\n");
      out.write("		</div>\n");
      out.write("		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/signUpAdmin.user\" method=\"post\" id=\"joinAdminForm\">\n");
      out.write("			<div class=\"join admin_table_div\">\n");
      out.write("				<table class=\"join admin_table\" border=\"1\">\n");
      out.write("					<tr>\n");
      out.write("						<th>아이디</th>\n");
      out.write("						<td>\n");
      out.write("							<input type=\"text\" id=\"admin_id\" class=\"joinInput\" name=\"id\" placeholder=\"영문 대/소문자, 숫자로 이루어진 4~10글자\"/>\n");
      out.write("						</td>\n");
      out.write("						<td class=\"infor_Td\" style=\"text-align: right\">\n");
      out.write("							<span class=\"table_In_Infor\" id=\"inforId\"></span>\n");
      out.write("						</td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<th>비밀번호</th>\n");
      out.write("						<td><input type=\"password\" id=\"admin_pwd\" class=\"joinInput\" name=\"pwd\" autocomplete=\"off\" placeholder=\"영문 대/소문자, 숫자, 특수문자로 이루어진 6~15글자\"/></td>\n");
      out.write("						<td class=\"infor_Td\" style=\"text-align: right; width: 225px;\"><label class=\"table_In_Infor\" id=\"inforPwd\"></label></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<th>비밀번호 확인</th>\n");
      out.write("						<td>\n");
      out.write("							<input type=\"password\" id=\"admin_rePwd\" class=\"joinInput\" name=\"rePwd\" autocomplete=\"off\" placeholder=\"필수 입력\"/>\n");
      out.write("						</td>\n");
      out.write("						<td class=\"infor_Td\" style=\"text-align: right;\">\n");
      out.write("							<label class=\"table_In_Infor\" id=\"inforRePwd\"></label>\n");
      out.write("						</td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<th>이름</th>\n");
      out.write("						<td colspan=\"2\"><input type=\"text\" id=\"admin_name\" class=\"joinInput\" name=\"name\" placeholder=\"한글 2~6글자 / 영문 2~18글자\"/></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<th>휴대폰번호</th>\n");
      out.write("						<td colspan=\"2\">\n");
      out.write("							<input type=\"text\" id=\"phone\" class=\"joinInput\" name=\"phone\" placeholder=\"- 포함 입력\"/>\n");
      out.write("							<input type=\"hidden\" name=\"address\" value=\"여기는§§●혼밥심\"/>\n");
      out.write("							<input type=\"hidden\" name=\"signupPath\" value=\"ADMIN\"/>\n");
      out.write("						</td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<th id=\"lastTrBTh\">관리자 비밀번호 인증</th>\n");
      out.write("						<td id=\"lastTrBTd\" colspan=\"2\"><input type=\"password\" id=\"adminPwd\" class=\"joinInput\" name=\"adminPwd\" placeholder=\"관리자 인증 비밀번호를 입력해 주세요.\"/></td>\n");
      out.write("					</tr>\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("			<div>\n");
      out.write("				<button id=\"admin_button\" type=\"button\">관리자 가입</button>\n");
      out.write("				<button id=\"join_go_button\" type=\"button\">일반회원 가입</button>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("	</div>	\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("		window.onload = () => {\n");
      out.write("			document.getElementById('join_go_button').addEventListener('click', () => {\n");
      out.write("				location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/joinView.user\";\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("			const inputs = document.getElementsByClassName('joinInput');\n");
      out.write("			let phone = document.getElementById('phone');\n");
      out.write("			const regPho = /^01([0|1|6|7|8|9])-([0-9]{3,4})-([0-9]{4})$/;\n");
      out.write("			let nameInput = document.getElementById('admin_name');\n");
      out.write("			const regName = /^([가-힣]{2,6}|[a-zA-Z]{2,18})$/ \n");
      out.write("		\n");
      out.write("			document.getElementById('admin_button').addEventListener('click', e => {			\n");
      out.write("				let count = 0;\n");
      out.write("				for(const input of inputs){\n");
      out.write("					if(input.value.trim() == ''){\n");
      out.write("						count++;\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("				\n");
      out.write("				if(count <= 6 && count > 0){\n");
      out.write("					alert('필수 항목을 입력해 주세요.');\n");
      out.write("					for(input of inputs){\n");
      out.write("						if(input.value == ''){\n");
      out.write("							input.focus();\n");
      out.write("						}\n");
      out.write("					}\n");
      out.write("				} else if(!pwdCheck()){\n");
      out.write("					alert('비밀번호가 일치하지 않습니다.');\n");
      out.write("					pwd.focus();\n");
      out.write("				} else if(inforPwd.innerText.includes('특수문자')){\n");
      out.write("					alert('다른 비밀번호를 입력해 주세요.');\n");
      out.write("					pwd.focus();\n");
      out.write("				} else if(inforId.innerText.includes('불가한')){\n");
      out.write("					alert('다른 아이디를 입력해 주세요.');\n");
      out.write("					idInput.focus();\n");
      out.write("				} else if(!regPho.test(phone.value)){\n");
      out.write("					alert('유효한 전화번호가 아닙니다. 다시 입력해 주세요.');\n");
      out.write("					phone.focus();\n");
      out.write("				} else if(!regName.test(nameInput.value)) {\n");
      out.write("					alert('이름을 다시 입력해 주세요.');\n");
      out.write("					nameInput.focus();\n");
      out.write("				} else if(count == 0 && pwdCheck() && inforId.innerText.includes('사용 가능한')) {\n");
      out.write("					document.querySelector(\"#joinAdminForm\").submit();\n");
      out.write("					\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		let pwd = document.getElementById('admin_pwd');\n");
      out.write("		let rePwd = document.getElementById('admin_rePwd');\n");
      out.write("		let inforPwd = document.getElementById('inforPwd');\n");
      out.write("		let inforRePwd = document.getElementById('inforRePwd');\n");
      out.write("		const inforId = document.getElementById('inforId');\n");
      out.write("		let idInput = document.getElementById('admin_id');\n");
      out.write("		const regId = /^[A-Za-z0-9]{4,10}$/;\n");
      out.write("		const regPwd = /^[A-Za-z0-9@.]{6,15}$/;\n");
      out.write("		\n");
      out.write("		idInput.addEventListener('focusout', checkId);\n");
      out.write("		pwd.addEventListener('focusout', pwdReg);\n");
      out.write("		rePwd.addEventListener('focusout', pwdCheck);\n");
      out.write("		\n");
      out.write("		function checkId(){\n");
      out.write("			let id = idInput.value;\n");
      out.write("			if(id.trim() != ''){\n");
      out.write("				$.ajax({\n");
      out.write("					url: 'checkId.user',\n");
      out.write("					data: {id:id},\n");
      out.write("					success: (data) => {\n");
      out.write("						if(data == 0 && regId.test(id)){\n");
      out.write("							inforId.innerText = '사용 가능한 아이디입니다';\n");
      out.write("							inforId.style.color = 'green';\n");
      out.write("							return true;\n");
      out.write("						} else {\n");
      out.write("							inforId.innerText = '사용 불가한 아이디입니다';\n");
      out.write("							inforId.style.color = 'red';\n");
      out.write("							return false;\n");
      out.write("						}\n");
      out.write("					},\n");
      out.write("					error: data => console.log(data)\n");
      out.write("				});\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function pwdCheck(){\n");
      out.write("			if(pwd.value === rePwd.value && (pwd.value.trim() != '' || rePwd.value.trim() != '')){\n");
      out.write("				inforRePwd.innerText = '비밀번호가 일치합니다';\n");
      out.write("				inforRePwd.style.color = 'green';\n");
      out.write("				return true;\n");
      out.write("			} else {\n");
      out.write("				inforRePwd.innerText = '비밀번호가 일치하지 않습니다';\n");
      out.write("				inforRePwd.style.color = 'red';\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function pwdReg(){\n");
      out.write("			if(!regPwd.test(pwd.value)){\n");
      out.write("				inforPwd.innerText = '비밀번호는 6~15자의 영문 대/소문자, 숫자, 특수문자를 사용해 주세요';\n");
      out.write("				inforPwd.style.color = 'red';\n");
      out.write("				return false;\n");
      out.write("			} else {\n");
      out.write("				inforPwd.innerText = '';\n");
      out.write("				return true;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("	</script>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
