/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-18 08:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1718959152000L));
    _jspx_dependants.put("jar:file:/D:/SemiProject_Honbapsim/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Semi_Project/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link href=\"resources/css/login_user.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #FFFBF2;\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"container\" class=\"text-center\" style=\"padding-bottom: 3rem !important;\">\r\n");
      out.write("		<div style=\"padding-top:1.5rem !important; padding-bottom:4rem !important;\" class=\"py-lg-5\">\r\n");
      out.write("   			<div id=\"login_bar\">\r\n");
      out.write("     			<p>로그인</p>\r\n");
      out.write("   			</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("   		<div id=\"id_join_find\">\r\n");
      out.write("   			<div id=\"id_join_find_box\">\r\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.user\" method=\"post\" id=\"login_form\">\r\n");
      out.write("					<div id=\"login\">\r\n");
      out.write("						<div id=\"login_box\">\r\n");
      out.write("							<div id=\"login_id\" class=\"login_content_name\">\r\n");
      out.write("								<input type=\"text\" id=\"id\" name=\"id\" class=\"login_content\"placeholder=\"아이디\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"login_pwd\" class=\"login_content_name\">\r\n");
      out.write("								<input type=\"password\" id=\"pwd\" name=\"pwd\" class=\"login_content\" placeholder=\"비밀번호\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"login_alert\" style=\"text-align: left; padding-left: 5px; padding-top: 5px;\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div id=\"login_check\">\r\n");
      out.write("							<button id=\"login_check_button\">로그인</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"hidden\" name=\"change\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ change }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("					<input type=\"hidden\" name=\"fail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("				</form>\r\n");
      out.write("				\r\n");
      out.write("				<div id=\"find_join\">\r\n");
      out.write("					<div id=\"find_join_box\">\r\n");
      out.write("						<div id=\"find_idpw\" class=\"find_join_in\">\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/findInfo.user\" id=\"find_idpw_link\" class=\"btn button_find_join\"><label class=\"font_text\">아이디/비밀번호 찾기</label></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div style=\"width: 40px; display: inline-block;\"></div>\r\n");
      out.write("						<div id=\"join_user\" class=\"find_join_in\">\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/joinView.user\" id=\"join_user_link\" class=\"button_find_join btn\"><label class=\"font_text\">회원가입</label></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = () => {\r\n");
      out.write("			const login = document.getElementById('login_check_button');\r\n");
      out.write("			const alertDiv = document.getElementById('login_alert');\r\n");
      out.write("			const id = document.getElementById('id');\r\n");
      out.write("			const pwd = document.getElementById('pwd');\r\n");
      out.write("			\r\n");
      out.write("			const findJoinBtn = document.getElementsByClassName('button_find_join');\r\n");
      out.write("			for(const btn of findJoinBtn){\r\n");
      out.write("				btn.addEventListener('mouseover', function(){\r\n");
      out.write("					const text = btn.children[0];\r\n");
      out.write("					text.style.cursor = 'pointer';\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			const fail = document.getElementsByName('fail')[0];\r\n");
      out.write("			if(fail.value == \"fail\"){\r\n");
      out.write("				alertDiv.innerText = '아이디와 비밀번호를 정확히 입력해 주세요.';\r\n");
      out.write("				alertDiv.style.color = 'red';\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty loginUser }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("				alert('로그인이 되어있습니다.');\r\n");
      out.write("				location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/recipe.re\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			const msg = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("			console.log(msg);\r\n");
      out.write("			if(msg != ''){\r\n");
      out.write("				alert(msg);\r\n");
      out.write("			}\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			login.onclick = e => {\r\n");
      out.write("				if(id.value.trim() == ''){\r\n");
      out.write("					alertDiv.innerText = '아이디를 입력하세요.';\r\n");
      out.write("					alertDiv.style.color = 'red';\r\n");
      out.write("					alertDiv.style.fontSize = '20px;'\r\n");
      out.write("					document.getElementById('login_id').style.border = '2px solid #F24822';\r\n");
      out.write("					document.getElementById('login_pwd').style.border = '1px solid lightgray';\r\n");
      out.write("					id.focus();\r\n");
      out.write("					e.preventDefault();\r\n");
      out.write("				} else if(pwd.value.trim() == ''){\r\n");
      out.write("					alertDiv.innerText = '비밀번호를 입력하세요.';\r\n");
      out.write("					alertDiv.style.color = 'red';\r\n");
      out.write("					alertDiv.style.fontSize = '20px;'\r\n");
      out.write("					document.getElementById('login_id').style.border = '1px solid lightgray';\r\n");
      out.write("					document.getElementById('login_pwd').style.border = '2px solid #F24822';\r\n");
      out.write("					pwd.focus();\r\n");
      out.write("					e.preventDefault();\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			\r\n");
      out.write("			id.addEventListener('focusin', function(){\r\n");
      out.write("				document.getElementById('login_id').style.border = '2px solid #F24822';\r\n");
      out.write("			});\r\n");
      out.write("			id.addEventListener('focusout', function(){\r\n");
      out.write("				document.getElementById('login_id').style.border = '1px solid lightgray';\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			pwd.addEventListener('focusin', function(){\r\n");
      out.write("				document.getElementById('login_pwd').style.border = '2px solid #F24822';\r\n");
      out.write("			});\r\n");
      out.write("			pwd.addEventListener('focusout', function(){\r\n");
      out.write("				document.getElementById('login_pwd').style.border = '1px solid lightgray';\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 session.removeAttribute("msg"); 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
